###此项为必配项：qd-server端口,必须保障未占用
server:
  port: 8082
spring:
  application:
    name: qd-server
  datasource:
    #DB用户名
    username: QD_PLATFORM
    #DB密码
    password: 1
    #DB连接
    url: jdbc:oracle:thin:@172.16.101.34:1521/orcl
    driverClassName: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池参数设置
    druid:
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 20
      min-idle: 20
      max-active: 200
      #配置获取连接等待超时的时间
      max-wait: 100000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      query-timeout: 0
      
      
  thymeleaf:
    # 默认true,开发是设置false,上线是设置为true以便提高性能
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  #    enabled: true
  #    check-template: false
 

# MyBatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml,classpath*:/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.qd.**.mapper
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 

## 日志
logging:
  config: classpath:log4j2.xml

#token令牌
token:
  # token超时时间默认为2个小时
  expire:
      seconds: 7200
  # token签名加密字符串
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)
  
## 资源类型
resource:
  type:
      http: http

 
file:
  #上传的服务器上的映射文件夹
  accessPath: /uploads/
  #静态资源对外暴露的访问路径
  staticAccessPath: /**
  #静态资源实际存储路径
  uploadFolder: D:\eclipse-workpace\qd_platform-workpace\qd-platform\uploads\

# 代码生成
generate:
  # 作者
  author: 周琦
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.qd.server
  # 模块名
  moduleName: qd-server
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: qd_   
